

CREATE TABLE SAVES (
	ID				INT						NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(100)			NOT NULL,
	DATE			VARCHAR(100)			NOT NULL,

	CONSTRAINT PK_SAVES PRIMARY KEY (ID)
);

CREATE TABLE FILES (
	ID				INT				NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(100)	NOT NULL,
	SIZE			INT				NOT NULL,
	HASH			VARCHAR(2000)	NOT NULL,

	CONSTRAINT PK_FILES PRIMARY KEY (ID)
);

CREATE TABLE BLOCKS (
	ID				INT				NOT NULL AUTO_INCREMENT,
	BLOCKNUMBER		INT				NOT NULL,
	VALUE			TEXT			NOT NULL,
	HASH			VARCHAR(2000)	NOT NULL,

	CONSTRAINT PK_BLOCKS PRIMARY KEY (ID)
);





CREATE TABLE SAVEDFILES (
	ID				INT				NOT NULL AUTO_INCREMENT,
	FILEID			int			NOT NULL,
	SAVEID			int			NOT NULL,
    LOCATION		VARCHAR(2000)			NOT NULL

	CONSTRAINT PK_SAVEDFILES   PRIMARY KEY (ID),
	CONSTRAINT FK_SAVE_BLOCK_F FOREIGN KEY (FILEID) REFERENCES FILES(ID),
	CONSTRAINT FK_SAVE_BLOCK_S FOREIGN KEY (SAVEID) REFERENCES SAVES(ID)
);


CREATE TABLE BLOCKSFILES (
	ID				INT				NOT NULL AUTO_INCREMENT,
	FILEID			int			NOT NULL,
	BLOCKID		int			NOT NULL,

	CONSTRAINT PK_BLOCKSFILES  PRIMARY KEY (ID),
	CONSTRAINT FK_BLOCK_FILE_F FOREIGN KEY (FILEID) REFERENCES FILES(ID),
	CONSTRAINT FK_BLOCK_FILE_B FOREIGN KEY (BLOCKID) REFERENCES BLOCKS(ID)
);
