---
- name: "Example playbook"
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: "Restore a folder"
    saver:
      save_name: "MySaveName"
      action: "restore"
      restore_date: "2020-06-06 22:29:54.461932"

      mysql_host: "localhost"
      mysql_user: "root"
      mysql_passwd: "mysql"
      mysql_db: "save"
      
      ftp_host: "172.17.0.2"
      ftp_user: "ftp"
      ftp_passwd: "ftp"
