---
- name: "Example playbook"
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: "Save a folder"
    saver:
      save_name: "MySaveName"
      action: "save"
      path_to_save: "/share/example-project"
      block_size: 512000
      
      mysql_host: "localhost"
      mysql_user: "root"
      mysql_passwd: "mysql"
      mysql_db: "save"
      
      ftp_host: "172.17.0.2"
      ftp_user: "ftp"
      ftp_passwd: "ftp"
